version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: make install
      - run:
          name: Run Tests
          command: make test
workflows:
  version: 2
  test:
    jobs:
      - test
